services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: personal_library
      MYSQL_USER: library_user
      MYSQL_PASSWORD: library_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10
  
  api:
    build:
      context: ./backend_/Library.Api
    environment:
      ConnectionStrings__DefaultConnection: "server=db;port=3306;database=personal_library;user=library_user;password=library_pass;"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5159:5159"
  
  frontend:
    image: nginx:stable-alpine
    volumes:
      - ./fontend_:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  db_data:
